config/routes.rb
Rails.application.routes.draw do
  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'
  
  get 'submit' => 'static_pages#submit'
  
  get 'blog' => 'blogposts#index'
  
  get 'new_post' => 'blogposts#new'
  
  get 'info' => 'static_pages#info'
  
  get 'admin' => 'blogposts#admin'
  
  get 'edit' => 'blogposts#edit'
  
  root 'static_pages#home'
  
  resources :blogposts

end

app/models/blogpost.rb
class Blogpost < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  http_basic_authenticate_with :name => "admin", :password => "password", :except => ['index']
  
  def show
    @blogpost = Blogpost.find(params[:id])
  end
  
  def new
    @blogpost = Blogpost.new
  end
  
  def edit
    @blogpost = Blogpost.find(params[:id])
  end
  
  def update
    @blogpost = Blogpost.find(params[:id])
    if @blogpost.update_attributes(post_params)
      flash.notice = "Post successfully updated"
      redirect_to admin_path
    else
      render 'edit'
    end
  end
  
  def create
    @blogpost = Blogpost.new(post_params)
    if @blogpost.save
      flash.notice = "Post successfully created"
      redirect_to admin_path
    else
      render 'new'
    end
  end
  
  def index
    @blogposts = Blogpost.all
  end
  
  def admin
    @blogposts = Blogpost.all
  end
  
  def destroy
    @blogpost = Blogpost.find(params[:id])
    @blogpost.destroy
    redirect_to admin_path
  end
  
  private

    def post_params
      params.require(:blogpost).permit(:title, :content)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end
  
  def home
  end
  
  def submit
  end
  
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/blogposts/_blogpost.html.erb
<li>
  <p>
    <span style="font-size:22px"><strong><%= blogpost.title %></strong></span>
  </p>
  
  <div class="muchtext">
    <p>
      <span class="content"><%= blogpost.content %></span>
    </p>
  </div
  
  <p>
    <span class="timestamp">
      Posted <%= time_ago_in_words(blogpost.created_at) %> ago.
    </span>
  </p>
  
  <br>
  <br>
</li>

app/views/blogposts/_edit_posts.html.erb
<li>
  <%= p.title %>
  <%= link_to "delete", p, method: :delete, data: { confirm: "You sure?" } %>
  <%= link_to "edit", p, method: :edit %>
</li>

app/views/blogposts/admin.html.erb
<p><%= link_to "Create new blog post", new_post_path %></p>
<br>

<p>Current Blog Posts:</p>

<ul>
  <%= @blogposts.each do |p| %>
    <li>
      <%= p.title %>
      <%= link_to "delete", p, method: :delete, data: { confirm: "You sure?" } %>
      <%= link_to "edit", edit_blogpost_path(p) %>
    </li>
  <% end %>
</ul>

app/views/blogposts/edit.html.erb
<h1>Update a blog post</h1>
<div class="narrow">
    
    <%= render 'shared/error_messages' %>
    
    <%= form_for @blogpost do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      
      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control' %>
      
      <%= f.submit %>
    <% end %>

</div>

app/views/blogposts/index.html.erb
<h1>Blog Posts</h1>
<ul>
  <%= render @blogposts %>
</ul>

app/views/blogposts/new.html.erb
<h1>Enter a new blog post</h1>
<div class="narrow">
    
    <%= render 'shared/error_messages' %>
    
    <%= form_for @blogpost do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      
      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control' %>
      
      <%= f.submit %>
    <% end %>

</div>

app/views/blogposts/show.html.erb
<%= render @blogpost %>

app/views/layouts/_footer.html.erb
<footer class="footer narrow">
  <small>Website (c) Luc Sinex 2015</small>
  <nav>
    <ul>
      <il><%= link_to "Contact Us  ", contact_path %></il>
      <il><%= link_to "Admin", admin_path %></il>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class = "header navbar navbar-fixed-top">
  <div class="container narrow">
    <%= link_to "CBJ Vs NMO", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Blog", blog_path %></li>
        <li><%= link_to "What is NMO?", info_path %></li>
        <li><%= link_to "About Us", about_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CBJ Vs NMO</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <div class="container narrow">
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>
    
    <%= yield %>
  </div>
  
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @blogpost.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@blogpost.errors.count, "error") %>.
    </div>
    <ul>
    <% @blogpost.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/_form.html.erb
<%= form_for @blogpost do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>About the Foundation</h1>

<h3 style="text-align:left">Connor's Story</h3>

<div class="muchtext">
  <p>
  Until August  2014, I considered myself a pretty normal 22-year old.  I felt young, 
  strong and completely healthy.  I even took advantage of my good health and shape, 
  and did heavy physical labor working in the landscaping business.  As any young person, 
  I never questioned that I would lose my health, or ability to do anything I pursued.  
  But in early August, things began to get a little weird. 
  </p>
  
  <p>
  I noticed a slight pain in both 
  my eyes, that would be triggered whenever I tried to gaze around me, without moving my head.  
  Eventually, my perfect 20/20 eyesight began to get a little blurry- I was pissed to say the least.  
  At about the same time, I started to experience a little tingling in my left leg.  
  I thought maybe I pulled something while working- I never once thought that my eye issues 
  and leg sensation were connected.  Why would I?  But since I was so used to being so healthy, 
  I started to get concerned, and made an appointment with a general family physician.  
  I was told that the eye pain and leg tingling, along with some mild back pain I was now feeling,
  were all probably due to “inflammation,” and I was given some basic anti-inflammatory, 
  over-the-counter pain killers.  
  </p>
  
  <div style="padding-top:50px; padding-bottom:50px; padding-left:225px"><%= image_tag("recovery.jpg", 
    alt: "Connor, Paige, and Chelsey at the Cleveland Clinic",
    height: "50%", width: "50%") %></div>
  
  <p>
  After about a week, my eye pain worsened, as did my back.  
  The tingling in my left leg turned to pain, and my right leg began to follow the same pattern… 
  I knew things were not right.  I stopped working for awhile, since I figured mulching and lifting a 
  shovel wouldn’t be practical to get rid of this pain… I saw another family physician, who once again
  said that I had “inflammation” and maybe glaucoma. I was referred to see an eye doctor (ophthalmologist) 
  and a neurologist.  At this point, my eyes were bad, especially my left- I could barely see.  
  My back ached.  My legs were in so much pain I could hardly walk, and I was taking hot baths every night, 
  to ease the pain (to no avail). I also started to notice that I wasn’t able to use the restroom-  
  couldn’t even get myself to pee.  On August 29th, after an intense night of pain, just a day after my 
  last doctor’s visit, I woke up, got out of bed… and fell unto my butt.  I could not use my legs at all.  
  As much as I hate to say this word, I was paralyzed from my belly button to my toes.  
  Asking my girlfriend to drive to the local ER, I crawled myself to my car.  What was wrong with me?
  </p>
  
  <p>
  After a 12 hour stint in the ER, in which the chief of the ER department ordered countless blood 
  tests and a spinal and brain MRI for me, I saw a neurologist.  He performed the first, after which
  I would have dozens, neurological assessment, making me touch my finger to his finger, follow his
  hands with me eyes, test my upper body strength and my now pitiful lower body strength.  I was
  unable to move my legs at all, and could not feel his needle pokes and prods from my belly button
  to my toes. He told me that he believed I had transverse myelitis, and that to confirm I would need
  a lumbar puncture, or spinal tap.   He described other possible diagnoses to me, including multiple 
  sclerosis (MS) and Devic’s disease, aka neuromyelitis optica (NMO). A current diagnosis could only be
  made after the results of the blood tests, spinal tap and MRIs.  I was terrified.
  </p>
  
  <p>
  The next couple days I spent Labor Day weekend in a hospital bed, waiting for the neurologist to 
  determine what exactly was wrong with my body.  In the interim, I was receiving high dose intravenous
  steroids to suppress whatever “inflammation” was messing with my nervous system.  A neuro-opthamologist 
  came into see me at one point, to help figure out what was wrong with my eye.  She added another
  possibility to my list of growing diagnoses- optic neuritis.  Needless to say, I was confused, but 
  felt confident that I could conquer whatever was wrong with me.  The neurologist finally stepped in 
  on Monday, and ruled that I had NMO.  Based off of my normal brain MRI, spinal MRI showing lesions
  in my spinal cord, case of optic neuritis, and presence of white blood cells (lymphocytes) in my
  cerebrospinal fluid (CSF), he was able to make this diagnosis. While he spouted a lot of details
  about the disease, I was just more focused on keeping a good, confident attitude to take on NMO.
  </p>
  
  <p>
  I was moved to main campus Cleveland Clinic, so I could be seen by multiple neurologists, 
  who may have had a better chance of seeing similar patients with such a rare disease.  I was 
  poked and prodded by a team of neurologists, infectious disease specialists and physical medicine
  doctors multiple times a day. While my eye sight was getting better, I was still unable to 
  move or feel my legs, or even much below my belly button at all. I still couldn’t control
  my restroom use, and hadn’t gone in nearly a week at this point.  I was becoming a pro at 
  maneuvering a foley catheter to maintain minimum discomfort.  To expand my treatment and 
  progress, I went through 5 rounds of plasmapheresis, or plasma exchange (PLEX), in order to 
  purify my body of all the “bad” inflammatory components that were creating the problem.  After 
  the first round of PLEX, it was magic- I could finally move my legs a bit! Being able to show 
  off my “wiggling,” a little movement of my legs, to my friends and family was unbelievable. 
  At that moment, I was confident I would walk again.
  </p>
  
  <p>
  After nearly two weeks in the hospital, I regained my ability to lift my legs ever so high
  and could now slightly feel below my belly button again.  While I still retained the foley catheter,
  I was gaining some progress.  My next task was to become strong again in physical therapy, 
  at a physical medicine and spinal rehab hospital.  Over the course of a couple weeks, with 
  the combination of oral steroids to suppress inflammation, intense work, adept physical and
  occupational therapists, and a determination to walk again, I made phenomenal progress.  
  I was becoming independent after nearly a month of relying on nurses and family members to 
  help me dress, go to the bathroom, shower… basically all daily routines.  But now, I didn’t 
  that kind of help anymore- which further uplifted my spirits.  This progress was haulted 
  after I experience a bladder and kidney infection, caused by the foley catheter.  In this time, 
  my oral steroid use ended, and I missed my appointment with my neurologist, as well as 
  a couple rounds of physical therapy.  
  </p>
  
  <p>
  After clearing my infection, I returned to the rehab
  hospital and channeled my energy to take on walking.  However, I began to notice a distinct 
  eye irritation, and after another day, realized I was once again experiencing slight eye pain 
  and blurriness.  I was adamant about speaking with my doctors, who decided it was best 
  for me to receive attention of a neurologist and ophthalmologist, to determine if I was 
  experience a relapse of the optic neuritis component of NMO.  Indeed, I was- possible due
  to the lack of any immune suppressant.  At this point, my family and I realized we had to 
  be vigilant about my healthcare.  I had to become even better at listening to my body and 
  attending to it.  With another bout of intravenous steroids followed by oral steroid tapering,
  my eyes recovered.  I refocused my attention on recuperating.   After a total of 6 weeks 
  in this intense inpatient physical therapy, I left the hospital using not a wheelchair, but a walker.
  </p>
  
  <p>
  I’m now fully recuperating at home, with the care and attention of my family and girlfriend. 
  I’m becoming increasingly independent and ever more hopeful.  I have just met with my
  Cleveland Clinic neurologist at the Mellen Center, to determine my treatment plan, 
  maintaining low level oral steroids and possible enrollment in a clinical trial.  I’ve
  transitioned from a walker to a cane, and think I have a nice strut to my walk now.  While 
  I have my bad days, intense back and leg pain mixed with spasms, and the occasional lack 
  of control of my bladder, I live on the good days and the progress I have made. I’m looking
  forward to going back to school. While NMO is a rare, scary disease in which your immune 
  system attacks your central nervous system, I am always confident in my ability to tackle NMO.
  </p>

</div>

app/views/static_pages/contact.html.erb
<h1>Contact Information</h1>
<p>Please contact us at contact@cbjfoundation.org</p>

app/views/static_pages/home.html.erb
<div class="center">
<!-- <h1>Welcome to the Connor B Judge Foundation website!</h1> -->
<p>
  <%= link_to image_tag("logo.png", alt: "CBJ vs NMO") %>
</p>
</div>

app/views/static_pages/info.html.erb
<h1>What is NMO?</h1>

<div class="muchtext">
  <p>Neuromyelitis Optica (NMO) aka Devic’s Disease (named after the doctor who initially discovered it), is a 
  rare neurological autoimmune disease- meaning the body’s own immune cells begin to attack components 
  of the nervous system, specifically the optic nerve and spinal cord.  NMO patients experience optic 
  neuritis (causing eye pain and vision loss), transverse myelitis (leading to limb weakness and paralysis), 
  as well as decreased sensation and loss of bladder and bowel control.</p>
  
  <p>NMO is a distinct disease from 
  multiple sclerosis (MS), normally sparing the brain and affecting a higher proportion of females to males (9:1).  
  NMO can specifically lead to the formation of pathogenic (disease-causing)  antibodies against aquaporin 4 
  (AQP4), or NMO-IgG, in the vast majority of patients, which is believed to be a mediator in spinal cord destruction. 
  While nearly 80% of NMO subjects have these antibodies, NMO patients without NMO-IgG have similar spinal 
  inflammation and  destruction. Further diverging from MS, in which patients most often have mild attacks with 
  good recovery, NMO attacks lead to severe disability, most often with incomplete recovery.</p>
</div>

<p>To learn more, please visit:</p>

<ul style='text-align:left'>
  <li><a href="http://www.mayo.edu/research/centers-programs/center-multiple-sclerosis-cns-demyelinating-diseases/
  neuromyelitis-optica-nmo-variant-multiple-sclerosis">The Mayo Clinic</a></li>

  <li><a href="http://www.ninds.nih.gov/disorders/neuromyelitis_optica/neuromyelitis_optica.htm">
    National Institute of Neurological Disorders and Stroke</a></li>
</ul>

app/views/static_pages/links.html.erb
<h1>StaticPages#links</h1>
<p>Find me in app/views/static_pages/links.html.erb</p>

app/views/static_pages/new.html.erb
<h1>Submit a new blog post</h1>

<%= render 'form' %>